package vistaControl;

import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import modelo.Alumno;
import persistencia.AlumnoData;

/**
 *
 * @author Grupo 19 (Matias Correa, Valeria Muñoz, Evelyn Cetera)
 */
public class FormularioAlumnoView extends javax.swing.JInternalFrame {

    private AlumnoData alumData;

    public FormularioAlumnoView(AlumnoData aData) {
        initComponents();
        this.alumData = aData;
        limpiarCampos();
        deshabilitarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estados = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jpFormulario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooserCalendario = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonActivo = new javax.swing.JRadioButton();
        jRadioButtonInactivo = new javax.swing.JRadioButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jpBajaAlta = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jbBaja = new javax.swing.JButton();
        jbAlta = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Alumnos");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 36), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        jTextFieldDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("DNI:");

        jTextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento:");

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Estado:");

        estados.add(jRadioButtonActivo);
        jRadioButtonActivo.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jRadioButtonActivo.setText("Activo");

        estados.add(jRadioButtonInactivo);
        jRadioButtonInactivo.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jRadioButtonInactivo.setText("Inactivo");

        javax.swing.GroupLayout jpFormularioLayout = new javax.swing.GroupLayout(jpFormulario);
        jpFormulario.setLayout(jpFormularioLayout);
        jpFormularioLayout.setHorizontalGroup(
            jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addGap(41, 41, 41)
                .addGroup(jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFormularioLayout.createSequentialGroup()
                        .addComponent(jRadioButtonActivo)
                        .addGap(36, 36, 36)
                        .addComponent(jRadioButtonInactivo))
                    .addComponent(jDateChooserCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFormularioLayout.setVerticalGroup(
            jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFormularioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFormularioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButtonActivo)
                    .addComponent(jRadioButtonInactivo))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButtonGuardar.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonBorrar.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonBorrar.setEnabled(false);
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonActualizar.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonActualizar.setEnabled(false);
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonLimpiar.setEnabled(false);
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonBuscar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTextFieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyTyped(evt);
            }
        });

        jLabelID.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabelID.setText("ID: ");

        jpBajaAlta.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("¿Dar de Baja/Alta?");

        jbBaja.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jbBaja.setText("BAJA");
        jbBaja.setEnabled(false);
        jbBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbBajaMouseClicked(evt);
            }
        });

        jbAlta.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jbAlta.setText("ALTA");
        jbAlta.setEnabled(false);
        jbAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAltaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpBajaAltaLayout = new javax.swing.GroupLayout(jpBajaAlta);
        jpBajaAlta.setLayout(jpBajaAltaLayout);
        jpBajaAltaLayout.setHorizontalGroup(
            jpBajaAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBajaAltaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jpBajaAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jpBajaAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbBaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAlta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jpBajaAltaLayout.setVerticalGroup(
            jpBajaAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBajaAltaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(jbBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jbAlta)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jpBajaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpBajaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpiar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here: --- OK 
        int id = Integer.valueOf(jTextFieldID.getText());
        Alumno alum = alumData.buscarAlumno(id);

        if (alum != null) {
            jTextFieldDNI.setText(alum.getDni() + "");
            jTextFieldNombre.setText(alum.getNombre());
            jTextFieldApellido.setText(alum.getApellido());
            jDateChooserCalendario.setDate(java.sql.Date.valueOf(alum.getFechaNacimiento()));
            actualizarEstado(alum.getEstado());

            jButtonGuardar.setEnabled(false);
            habilitarBotones();
            
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ningún alumno con ese ID" + id);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        //-------------REVISAR---------------
        try {
            //valido campos vacios antes de guardar
            if (jTextFieldDNI.getText().isEmpty() || jTextFieldNombre.getText().isEmpty()
                    || jTextFieldApellido.getText().isEmpty() || jDateChooserCalendario.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios" + JOptionPane.WARNING_MESSAGE);
                return;
            }

            int dni = Integer.valueOf(jTextFieldDNI.getText());
            String nombre = jTextFieldNombre.getText();
            String apellido = jTextFieldApellido.getText();
            boolean estado = jRadioButtonActivo.isSelected();

            LocalDate fechaNac = jDateChooserCalendario.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            Alumno alum = new Alumno(dni, nombre, apellido, fechaNac, estado);
            alumData.guardarAlumno(alum);

            jTextFieldID.setText(alum.getIdAlumno() + "");
            JOptionPane.showMessageDialog(this, "Alumno guardado correctamente!");
            limpiarCampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El campo DNI debe ser de valor númerico" + e.getMessage());
        }

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:                
        

        //---------REVISAR----------------
        int id = Integer.valueOf(jTextFieldID.getText());
        int dni = Integer.valueOf(jTextFieldDNI.getText());
        String nombre = jTextFieldNombre.getText();
        String apellido = jTextFieldApellido.getText();
        boolean estado = jRadioButtonActivo.isSelected();

        LocalDate fechaNac = jDateChooserCalendario.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Alumno alum = new Alumno(dni, nombre, apellido, fechaNac, estado);
        alum.setIdAlumno(id);

        alumData.actualizarAlumno(alum);
        limpiarCampos();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        //----------------REVISAR -------------------
        int id = Integer.valueOf(jTextFieldID.getText());
        Alumno alum = new Alumno();
        alum.setIdAlumno(id);

        alumData.eliminarAlumno(alum);
        limpiarCampos();
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here: ---------OK
        limpiarCampos();
        deshabilitarBotones();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextFieldIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyTyped
        // TODO add your handling code here: -------------OK
        jButtonBuscar.setEnabled(true);
        char id = evt.getKeyChar();

        validarNumeros(id, evt);
        jTextFieldID.requestFocus();

        if (jTextFieldID.getText().length() >= 5) {
            JOptionPane.showMessageDialog(this, "5 digitos permitidos", "Warning", JOptionPane.WARNING_MESSAGE);
            evt.consume();
            jTextFieldID.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldIDKeyTyped

    private void jTextFieldDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIKeyTyped
        // TODO add your handling code here: -----------------OK
        jButtonGuardar.setEnabled(true);
        char dni = evt.getKeyChar();

        validarNumeros(dni, evt);
        jTextFieldDNI.requestFocus();

        if (jTextFieldDNI.getText().length() >= 10) {
            JOptionPane.showMessageDialog(this, "10 digitos permitidos", "Warning", JOptionPane.WARNING_MESSAGE);
            evt.consume();
            jTextFieldID.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldDNIKeyTyped

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        // TODO add your handling code here: ----------OK
        char c = evt.getKeyChar();
        validarLetras(c, evt);
        jTextFieldNombre.requestFocus();
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoKeyTyped
        // TODO add your handling code here: ------------OK
        char c = evt.getKeyChar();
        validarLetras(c, evt);
        jTextFieldNombre.requestFocus();
    }//GEN-LAST:event_jTextFieldApellidoKeyTyped

    private void jbBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBajaMouseClicked
        // TODO add your handling code here: ---------------OK
        int id = Integer.valueOf(jTextFieldID.getText());//traigo el id
        Alumno a = alumData.buscarAlumno(id);//lo asigno a una variable de tipo Alumno usando el metodo de buscar alumno que recibe un id

        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea darse de baja?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
            alumData.bajaAlumno(a);//y se lo paso por parametro al metodo de baja!    
        } else {
            JOptionPane.showMessageDialog(this, "Confirmación cancelada");
        }
        alumData.buscarAlumno(id);
        actualizarEstado(a.getEstado());
    }//GEN-LAST:event_jbBajaMouseClicked

    private void jbAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAltaMouseClicked
        // TODO add your handling code here: -----------------OK
        int id = Integer.valueOf(jTextFieldID.getText());
        Alumno a = alumData.buscarAlumno(id);

        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea darse de alta?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
            alumData.altaAlumno(a);
        } else {
            JOptionPane.showMessageDialog(this, "Confirmación cancelada");
        }
        alumData.buscarAlumno(id);
        actualizarEstado(a.getEstado());
    }//GEN-LAST:event_jbAltaMouseClicked
    private void limpiarCampos() {
        //vaciamos campos
        jTextFieldID.setText("");
        jTextFieldDNI.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jDateChooserCalendario.setDate(null);
        estados.clearSelection();
    }

    private void deshabilitarBotones() {
        jButtonBuscar.setEnabled(false);
        jButtonGuardar.setEnabled(false);
        jButtonBorrar.setEnabled(false);
        jButtonActualizar.setEnabled(false);
        jButtonLimpiar.setEnabled(false);
        jbAlta.setEnabled(false);
        jbBaja.setEnabled(false);
    }
    private void habilitarBotones(){
        jButtonBuscar.setEnabled(true);
        jButtonGuardar.setEnabled(true);
        jButtonBorrar.setEnabled(true);
        jButtonActualizar.setEnabled(true);
        jButtonLimpiar.setEnabled(true);
        jbAlta.setEnabled(true);
        jbBaja.setEnabled(true);
    
    }

    private void validarLetras(char c, KeyEvent e) {
        if (Character.isDigit(c)) {
            JOptionPane.showMessageDialog(this, "No se permiten números en este campo", "Entrada inválida", JOptionPane.WARNING_MESSAGE);
            e.consume();
        }
    }

    private void validarNumeros(char c, KeyEvent e) {
        if (Character.isLetter(c)) {
            JOptionPane.showMessageDialog(this, "Campo de valores númericos", "Entrada inválida", JOptionPane.WARNING_MESSAGE);
            e.consume();
        }
    }
    public void actualizarEstado(boolean estado){
            jRadioButtonActivo.setSelected(estado);
            jRadioButtonInactivo.setSelected(!estado);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup estados;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private com.toedter.calendar.JDateChooser jDateChooserCalendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JRadioButton jRadioButtonActivo;
    private javax.swing.JRadioButton jRadioButtonInactivo;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JPanel jpBajaAlta;
    private javax.swing.JPanel jpFormulario;
    // End of variables declaration//GEN-END:variables

}
