
package vistaControl;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Inscripcion;
import modelo.Materia;
import persistencia.AlumnoData;
import persistencia.InscripcionData;
import persistencia.MateriaData;

/**
 *
 * @author Grupo 19 (Matias Correa, Valeria Muñoz, Evelyn Cetera)
 */
public class FormularioInscripcionView extends javax.swing.JInternalFrame {

    private AlumnoData alumnoData;
    private MateriaData materiaData;
    private InscripcionData inscripcionesData;
    private List<Alumno> listaAlumnos;
    private DefaultTableModel modelo = new DefaultTableModel();

    public FormularioInscripcionView(AlumnoData aluData, MateriaData matData, InscripcionData insData) {
        initComponents();
        alumnoData = aluData;
        materiaData = matData;
        inscripcionesData = insData;
        listaAlumnos = alumnoData.listarAlumnos();
        
        cargarComboBox();
        armarEncabezado();
        cargarTabla();
        
        jcbAlumnos.setSelectedIndex(-1);
        jbInscribir.setEnabled(false);
        jbAnularInsc.setEnabled(false);
        jrbInscriptas.setEnabled(false);
        jrbNoInscriptas.setEnabled(false);
    }

    private void cargarComboBox() {
        
        for (Alumno aux : listaAlumnos) {
            jcbAlumnos.addItem(aux);
        }
    }

    private void armarEncabezado() {

        modelo.addColumn("ID Inscripción");
        modelo.addColumn("Materia");
        modelo.addColumn("Año");
        modelo.addColumn("Nota");
        
        jtTablaMaterias.setModel(modelo);
    }
    
    private void cargarTabla() {
        modelo.setRowCount(0);
        modelo.fireTableDataChanged();

        Alumno seleccionado = (Alumno) jcbAlumnos.getSelectedItem();
        
        

        if (jrbNoInscriptas.isSelected()) {
            List<Materia> lista = inscripcionesData.listarMateriasNoCursadas(seleccionado.getIdAlumno());

            for (Materia m : lista) {
                modelo.addRow(new Object[]{
                    m.getIdMateria(),
                    m.getNombre(),
                    m.getAnio(),
                    " - "
                });
            }
        } else if(jrbInscriptas.isSelected()){
            List<Inscripcion> listaInsc = inscripcionesData.obtenerInscripciones(seleccionado.getIdAlumno());
            for (Inscripcion ins : listaInsc) {

                int idMat = ins.getIdMateria();
                Materia materia = materiaData.buscarMateria(idMat);
                if (materia != null) {
                    modelo.addRow(new Object[]{
                        ins.getIdInscripto(),
                        materia.getNombre(),
                        materia.getAnio(),
                        ins.getNota()}
                    );
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbAlumnos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jrbInscriptas = new javax.swing.JRadioButton();
        jrbNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaMaterias = new javax.swing.JTable();
        jbInscribir = new javax.swing.JButton();
        jbAnularInsc = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Inscripciones");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Inscripción");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(153, 153, 153)));
        jLabel1.setEnabled(false);
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Alumno: ");
        jLabel2.setEnabled(false);

        jcbAlumnos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jcbAlumnos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbAlumnosItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Materias: ");
        jLabel3.setEnabled(false);

        jrbInscriptas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jrbInscriptas.setText("Inscriptas");
        jrbInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInscriptasActionPerformed(evt);
            }
        });

        jrbNoInscriptas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jrbNoInscriptas.setText("No Inscriptas");
        jrbNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNoInscriptasActionPerformed(evt);
            }
        });

        jtTablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTablaMaterias);
        if (jtTablaMaterias.getColumnModel().getColumnCount() > 0) {
            jtTablaMaterias.getColumnModel().getColumn(0).setResizable(false);
            jtTablaMaterias.getColumnModel().getColumn(1).setResizable(false);
        }

        jbInscribir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbInscribir.setText("Inscribir");
        jbInscribir.setEnabled(false);
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbAnularInsc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbAnularInsc.setText("Anular Inscripción");
        jbAnularInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbInscriptas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jrbNoInscriptas)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jbInscribir)
                        .addGap(45, 45, 45)
                        .addComponent(jbAnularInsc, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jrbInscriptas)
                    .addComponent(jrbNoInscriptas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInscribir)
                    .addComponent(jbAnularInsc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInscriptasActionPerformed
        // TODO add your handling code here:
        //------------Radio Button-------------
        
        jrbNoInscriptas.setSelected(false);
        jbAnularInsc.setEnabled(true);
        jbInscribir.setEnabled(false);
        cargarTabla();
    }//GEN-LAST:event_jrbInscriptasActionPerformed

    private void jrbNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNoInscriptasActionPerformed
        // TODO add your handling code here:
        //------------Radio Button-------------
        
        jrbInscriptas.setSelected(false);
        jbAnularInsc.setEnabled(false);
        jbInscribir.setEnabled(true);
        cargarTabla();
        
    }//GEN-LAST:event_jrbNoInscriptasActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        // TODO add your handling code here:
        
        Alumno a =  (Alumno) jcbAlumnos.getSelectedItem();
        int idAlum = a.getIdAlumno();
        
        int filaSelec = jtTablaMaterias.getSelectedRow();
        if(filaSelec != -1){
            int idMat = (Integer)modelo.getValueAt(filaSelec, 0);

            Inscripcion ins = new Inscripcion(0.0, idAlum, idMat);
            inscripcionesData.guardarInscripciones(ins);
            cargarTabla();
            JOptionPane.showMessageDialog(this, "Inscripción realizada!");
            
        }else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbAnularInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscActionPerformed
        // TODO add your handling code here:
        int selec = jtTablaMaterias.getSelectedRow();
        
        Alumno a =  (Alumno) jcbAlumnos.getSelectedItem();
        int idAlum = a.getIdAlumno();
        int filaSelec = jtTablaMaterias.getSelectedRow();
        
        if(filaSelec != -1){
            int idMat = (Integer)modelo.getValueAt(filaSelec, 0);
            
            inscripcionesData.borrarInscripcion(idAlum, idMat);
            cargarTabla();
            JOptionPane.showMessageDialog(this, "Inscripción anulada", "Message", JOptionPane.INFORMATION_MESSAGE);
            
        }else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbAnularInscActionPerformed

    private void jcbAlumnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbAlumnosItemStateChanged
        // TODO add your handling code here:
        cargarTabla();
        jrbInscriptas.setEnabled(true);
        jrbNoInscriptas.setEnabled(true);
    }//GEN-LAST:event_jcbAlumnosItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnularInsc;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JComboBox<Alumno> jcbAlumnos;
    private javax.swing.JRadioButton jrbInscriptas;
    private javax.swing.JRadioButton jrbNoInscriptas;
    private javax.swing.JTable jtTablaMaterias;
    // End of variables declaration//GEN-END:variables
}
