package vistaControl;

import persistencia.AlumnoData;
import persistencia.Conexion;
import persistencia.InscripcionData;
import persistencia.MateriaData;

/**
 *
 * @author Grupo 19 (Matias Correa, Valeria Muñoz, Evelyn Cetera)
 */
public class MenuPrincipalView extends javax.swing.JFrame {

    private Conexion conexion;
    private AlumnoData alumnoData;
    private MateriaData materiaData;
    private InscripcionData inscripcionData;
    
    public MenuPrincipalView() {
        initComponents();
        
        conexion = new Conexion("jdbc:mariadb://localhost/GP19_bd_universidad", "root", "");
        alumnoData = new AlumnoData(conexion);
        materiaData = new MateriaData(conexion);
        inscripcionData = new InscripcionData(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInscripciones = new javax.swing.JMenu();
        jmiInscripciones = new javax.swing.JMenuItem();
        ListaInscripcionView = new javax.swing.JMenuItem();
        jMenuAlumnos = new javax.swing.JMenu();
        jMIFormAlumnos = new javax.swing.JMenuItem();
        jMenuMateria = new javax.swing.JMenu();
        jmiFormularioMateria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 839, Short.MAX_VALUE)
        );

        jMenuInscripciones.setText("Inscripciones");

        jmiInscripciones.setText("Formulario Inscripciones");
        jmiInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInscripcionesActionPerformed(evt);
            }
        });
        jMenuInscripciones.add(jmiInscripciones);

        ListaInscripcionView.setText("Lista Inscripciones");
        ListaInscripcionView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaInscripcionViewActionPerformed(evt);
            }
        });
        jMenuInscripciones.add(ListaInscripcionView);

        jMenuBar1.add(jMenuInscripciones);

        jMenuAlumnos.setText("Alumnos");

        jMIFormAlumnos.setText("Formulario Alumno");
        jMIFormAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormAlumnosActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMIFormAlumnos);

        jMenuBar1.add(jMenuAlumnos);

        jMenuMateria.setText("Materia");

        jmiFormularioMateria.setText("Formulario Materia");
        jmiFormularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioMateriaActionPerformed(evt);
            }
        });
        jMenuMateria.add(jmiFormularioMateria);

        jMenuBar1.add(jMenuMateria);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIFormAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormAlumnosActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        FormularioAlumnoView fav = new FormularioAlumnoView(alumnoData);
        Escritorio.add(fav);
        fav.setVisible(true);
        fav.moveToFront();
        
    }//GEN-LAST:event_jMIFormAlumnosActionPerformed

    private void jmiFormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioMateriaActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        FormularioMateriaView fmv = new FormularioMateriaView(materiaData);
        Escritorio.add(fmv);
        fmv.setVisible(true);
        fmv.moveToFront();
    }//GEN-LAST:event_jmiFormularioMateriaActionPerformed

    private void jmiInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInscripcionesActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        FormularioInscripcionView fim = new FormularioInscripcionView(alumnoData, materiaData, inscripcionData);
        Escritorio.add(fim);
        fim.setVisible(true);
        fim.moveToFront();
    }//GEN-LAST:event_jmiInscripcionesActionPerformed

    private void ListaInscripcionViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaInscripcionViewActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        ListaInscripcionView liv = new ListaInscripcionView(inscripcionData,alumnoData, materiaData);
        Escritorio.add(liv);
        liv.setVisible(true);
        liv.moveToFront();
    }//GEN-LAST:event_ListaInscripcionViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem ListaInscripcionView;
    private javax.swing.JMenuItem jMIFormAlumnos;
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInscripciones;
    private javax.swing.JMenu jMenuMateria;
    private javax.swing.JMenuItem jmiFormularioMateria;
    private javax.swing.JMenuItem jmiInscripciones;
    // End of variables declaration//GEN-END:variables
}
